# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
stay_list = [{
    "name": "Meles meles",
    "slug": "grid-enabled",
    "description": "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
    "location": "59 Hoffman Trail",
    "price": 62.79,
    "image": "http://dummyimage.com/171x224.bmp/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/205x182.jpg/dddddd/000000",
    "max_guests": 4,
    "pet_friendly": false,
    "pool": false,
    "wifi": false
  }, {
    "name": "Limosa haemastica",
    "slug": "tertiary",
    "description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.",
    "location": "1532 Everett Street",
    "price": 36.0,
    "image": "http://dummyimage.com/168x150.png/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/118x202.png/ff4444/ffffff",
    "max_guests": 4,
    "pet_friendly": true,
    "pool": true,
    "wifi": true
  }, {
    "name": "Varanus salvator",
    "slug": "Exclusive",
    "description": "Curabitur convallis.",
    "location": "2717 Eastlawn Place",
    "price": 34.2,
    "image": "http://dummyimage.com/114x227.png/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/201x210.png/dddddd/000000",
    "max_guests": 4,
    "pet_friendly": false,
    "pool": true,
    "wifi": true
  }, {
    "name": "Plegadis falcinellus",
    "slug": "monitoring",
    "description": "Aliquam sit amet diam in magna bibendum imperdiet.",
    "location": "92954 Coolidge Point",
    "price": 49.96,
    "image": "http://dummyimage.com/197x204.jpg/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/150x230.jpg/cc0000/ffffff",
    "max_guests": 4,
    "pet_friendly": false,
    "pool": true,
    "wifi": false
  }, {
    "name": "Gabianus pacificus",
    "slug": "Digitized",
    "description": "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
    "location": "09 Kennedy Center",
    "price": 63.06,
    "image": "http://dummyimage.com/113x206.png/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/172x213.png/ff4444/ffffff",
    "max_guests": 4,
    "pet_friendly": false,
    "pool": false,
    "wifi": false
  }, {
    "name": "Eumetopias jubatus",
    "slug": "complexity",
    "description": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "location": "6102 Pond Park",
    "price": 33.59,
    "image": "http://dummyimage.com/233x152.bmp/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/130x154.png/ff4444/ffffff",
    "max_guests": 4,
    "pet_friendly": true,
    "pool": true,
    "wifi": false
  }, {
    "name": "Phaethon aethereus",
    "slug": "installation",
    "description": "In sagittis dui vel nisl. Duis ac nibh.",
    "location": "6 Brown Alley",
    "price": 62.2,
    "image": "http://dummyimage.com/126x224.bmp/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/140x238.png/5fa2dd/ffffff",
    "max_guests": 8,
    "pet_friendly": true,
    "pool": true,
    "wifi": false
  }, {
    "name": "Priodontes maximus",
    "slug": "task-force",
    "description": "Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.",
    "location": "3 Holy Cross Avenue",
    "price": 58.48,
    "image": "http://dummyimage.com/153x128.png/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/130x151.jpg/ff4444/ffffff",
    "max_guests": 2,
    "pet_friendly": true,
    "pool": true,
    "wifi": false
  }, {
    "name": "Pandon haliaetus",
    "slug": "3rd generation",
    "description": "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    "location": "8 South Hill",
    "price": 66.25,
    "image": "http://dummyimage.com/124x199.bmp/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/111x191.jpg/dddddd/000000",
    "max_guests": 8,
    "pet_friendly": true,
    "pool": true,
    "wifi": true
  }, {
    "name": "Halcyon smyrnesis",
    "slug": "executive",
    "description": "Nam tristique tortor eu pede.",
    "location": "83 Fieldstone Terrace",
    "price": 30.33,
    "image": "http://dummyimage.com/143x221.jpg/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/146x109.jpg/ff4444/ffffff",
    "max_guests": 5,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Boa caninus",
    "slug": "client-driven",
    "description": "In quis justo. Maecenas rhoncus aliquam lacus.",
    "location": "6257 Esker Terrace",
    "price": 54.99,
    "image": "http://dummyimage.com/235x179.bmp/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/211x191.jpg/ff4444/ffffff",
    "max_guests": 7,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Recurvirostra avosetta",
    "slug": "contingency",
    "description": "Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "location": "9 Kennedy Hill",
    "price": 42.22,
    "image": "http://dummyimage.com/179x208.bmp/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/116x115.bmp/cc0000/ffffff",
    "max_guests": 3,
    "pet_friendly": false,
    "pool": true,
    "wifi": false
  }, {
    "name": "Chlidonias leucopterus",
    "slug": "Synchronised",
    "description": "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
    "location": "00346 Melby Point",
    "price": 63.95,
    "image": "http://dummyimage.com/148x216.png/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/113x142.png/dddddd/000000",
    "max_guests": 3,
    "pet_friendly": true,
    "pool": true,
    "wifi": true
  }, {
    "name": "Crocuta crocuta",
    "slug": "adapter",
    "description": "Nulla tellus.",
    "location": "798 Jenifer Plaza",
    "price": 36.15,
    "image": "http://dummyimage.com/135x170.png/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/195x181.bmp/5fa2dd/ffffff",
    "max_guests": 7,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Columba palumbus",
    "slug": "Quality-focused",
    "description": "Quisque ut erat.",
    "location": "29076 Gina Center",
    "price": 43.06,
    "image": "http://dummyimage.com/218x189.jpg/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/106x211.bmp/cc0000/ffffff",
    "max_guests": 4,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Hystrix cristata",
    "slug": "archive",
    "description": "Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.",
    "location": "4159 Toban Court",
    "price": 42.37,
    "image": "http://dummyimage.com/184x186.png/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/151x226.jpg/5fa2dd/ffffff",
    "max_guests": 7,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Echimys chrysurus",
    "slug": "portal",
    "description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    "location": "02096 Debra Plaza",
    "price": 41.79,
    "image": "http://dummyimage.com/125x211.jpg/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/188x218.jpg/5fa2dd/ffffff",
    "max_guests": 3,
    "pet_friendly": true,
    "pool": true,
    "wifi": false
  }, {
    "name": "Macropus eugenii",
    "slug": "Front-line",
    "description": "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    "location": "96 Melby Parkway",
    "price": 58.87,
    "image": "http://dummyimage.com/156x218.bmp/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/186x227.jpg/dddddd/000000",
    "max_guests": 8,
    "pet_friendly": true,
    "pool": true,
    "wifi": true
  }, {
    "name": "Nasua narica",
    "slug": "needs-based",
    "description": "Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "location": "3872 Green Pass",
    "price": 32.95,
    "image": "http://dummyimage.com/161x180.png/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/169x221.png/cc0000/ffffff",
    "max_guests": 6,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Stenella coeruleoalba",
    "slug": "global",
    "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    "location": "761 Swallow Alley",
    "price": 64.15,
    "image": "http://dummyimage.com/243x160.bmp/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/140x169.png/cc0000/ffffff",
    "max_guests": 5,
    "pet_friendly": false,
    "pool": true,
    "wifi": true
  }, {
    "name": "Tragelaphus strepsiceros",
    "slug": "Seamless",
    "description": "Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
    "location": "79 Tony Street",
    "price": 54.39,
    "image": "http://dummyimage.com/230x165.jpg/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/128x200.png/5fa2dd/ffffff",
    "max_guests": 8,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Larus fuliginosus",
    "slug": "Multi-channelled",
    "description": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
    "location": "7 Kipling Way",
    "price": 58.84,
    "image": "http://dummyimage.com/112x101.png/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/218x234.jpg/ff4444/ffffff",
    "max_guests": 8,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Equus burchelli",
    "slug": "service-desk",
    "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    "location": "2 Arizona Circle",
    "price": 32.25,
    "image": "http://dummyimage.com/164x192.bmp/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/145x102.jpg/5fa2dd/ffffff",
    "max_guests": 5,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Dipodomys deserti",
    "slug": "6th generation",
    "description": "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    "location": "39 Manley Road",
    "price": 48.91,
    "image": "http://dummyimage.com/246x103.png/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/149x225.jpg/5fa2dd/ffffff",
    "max_guests": 2,
    "pet_friendly": false,
    "pool": true,
    "wifi": false
  }, {
    "name": "Macropus rufus",
    "slug": "leverage",
    "description": "Duis aliquam convallis nunc.",
    "location": "1763 Merrick Street",
    "price": 53.05,
    "image": "http://dummyimage.com/107x176.png/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/142x211.jpg/ff4444/ffffff",
    "max_guests": 5,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Haematopus ater",
    "slug": "Fully-configurable",
    "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
    "location": "012 Veith Plaza",
    "price": 30.37,
    "image": "http://dummyimage.com/218x144.png/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/185x124.jpg/5fa2dd/ffffff",
    "max_guests": 6,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Papilio canadensis",
    "slug": "middleware",
    "description": "Nulla nisl.",
    "location": "4 Mendota Avenue",
    "price": 40.88,
    "image": "http://dummyimage.com/103x144.jpg/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/192x242.jpg/5fa2dd/ffffff",
    "max_guests": 7,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Vulpes chama",
    "slug": "Multi-lateral",
    "description": "Nullam porttitor lacus at turpis.",
    "location": "81 Eastlawn Lane",
    "price": 61.81,
    "image": "http://dummyimage.com/145x238.png/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/100x198.bmp/cc0000/ffffff",
    "max_guests": 7,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Creagrus furcatus",
    "slug": "Multi-lateral",
    "description": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.",
    "location": "2 Washington Junction",
    "price": 65.87,
    "image": "http://dummyimage.com/191x250.png/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/109x114.png/5fa2dd/ffffff",
    "max_guests": 3,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Cynomys ludovicianus",
    "slug": "extranet",
    "description": "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "location": "70444 Sunbrook Drive",
    "price": 34.11,
    "image": "http://dummyimage.com/200x109.jpg/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/182x122.jpg/ff4444/ffffff",
    "max_guests": 5,
    "pet_friendly": false,
    "pool": false,
    "wifi": false
  }, {
    "name": "Ninox superciliaris",
    "slug": "contingency",
    "description": "In hac habitasse platea dictumst.",
    "location": "6 Manley Court",
    "price": 41.82,
    "image": "http://dummyimage.com/239x211.png/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/234x176.png/5fa2dd/ffffff",
    "max_guests": 5,
    "pet_friendly": true,
    "pool": true,
    "wifi": false
  }, {
    "name": "Cordylus giganteus",
    "slug": "Distributed",
    "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    "location": "37658 Golf Course Street",
    "price": 45.63,
    "image": "http://dummyimage.com/118x242.jpg/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/211x132.png/cc0000/ffffff",
    "max_guests": 5,
    "pet_friendly": false,
    "pool": true,
    "wifi": true
  }, {
    "name": "Alcelaphus buselaphus cokii",
    "slug": "high-level",
    "description": "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "location": "8 Bluejay Pass",
    "price": 36.47,
    "image": "http://dummyimage.com/237x210.png/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/226x127.jpg/ff4444/ffffff",
    "max_guests": 8,
    "pet_friendly": false,
    "pool": true,
    "wifi": true
  }, {
    "name": "Ploceus rubiginosus",
    "slug": "alliance",
    "description": "Ut tellus.",
    "location": "35704 Hallows Crossing",
    "price": 50.76,
    "image": "http://dummyimage.com/168x156.bmp/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/177x111.png/5fa2dd/ffffff",
    "max_guests": 4,
    "pet_friendly": false,
    "pool": true,
    "wifi": false
  }, {
    "name": "Panthera leo persica",
    "slug": "context-sensitive",
    "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    "location": "04 Kenwood Trail",
    "price": 52.61,
    "image": "http://dummyimage.com/150x156.png/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/113x234.bmp/dddddd/000000",
    "max_guests": 8,
    "pet_friendly": false,
    "pool": true,
    "wifi": true
  }, {
    "name": "Chelodina longicollis",
    "slug": "Graphic Interface",
    "description": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    "location": "0 Manufacturers Street",
    "price": 64.52,
    "image": "http://dummyimage.com/109x224.png/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/171x223.png/5fa2dd/ffffff",
    "max_guests": 7,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Phascogale calura",
    "slug": "infrastructure",
    "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    "location": "38 Cody Road",
    "price": 39.64,
    "image": "http://dummyimage.com/169x174.bmp/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/202x117.png/ff4444/ffffff",
    "max_guests": 8,
    "pet_friendly": false,
    "pool": false,
    "wifi": false
  }, {
    "name": "Lybius torquatus",
    "slug": "strategy",
    "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    "location": "65 Dixon Street",
    "price": 52.93,
    "image": "http://dummyimage.com/163x202.png/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/182x209.jpg/ff4444/ffffff",
    "max_guests": 3,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Felis silvestris lybica",
    "slug": "task-force",
    "description": "Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    "location": "7 Helena Park",
    "price": 62.29,
    "image": "http://dummyimage.com/172x228.png/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/245x206.png/5fa2dd/ffffff",
    "max_guests": 4,
    "pet_friendly": true,
    "pool": false,
    "wifi": false
  }, {
    "name": "Paraxerus cepapi",
    "slug": "intangible",
    "description": "Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    "location": "0156 Bashford Road",
    "price": 61.14,
    "image": "http://dummyimage.com/132x177.png/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/231x136.bmp/dddddd/000000",
    "max_guests": 7,
    "pet_friendly": true,
    "pool": true,
    "wifi": false
  }, {
    "name": "Aepyceros mylampus",
    "slug": "Focused",
    "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    "location": "205 6th Junction",
    "price": 39.82,
    "image": "http://dummyimage.com/105x236.png/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/122x191.jpg/ff4444/ffffff",
    "max_guests": 4,
    "pet_friendly": true,
    "pool": true,
    "wifi": false
  }, {
    "name": "Acrantophis madagascariensis",
    "slug": "Multi-tiered",
    "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.",
    "location": "21 Graceland Pass",
    "price": 54.03,
    "image": "http://dummyimage.com/126x235.bmp/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/190x170.jpg/ff4444/ffffff",
    "max_guests": 3,
    "pet_friendly": false,
    "pool": false,
    "wifi": false
  }, {
    "name": "Centrocercus urophasianus",
    "slug": "mobile",
    "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    "location": "439 Carberry Street",
    "price": 69.43,
    "image": "http://dummyimage.com/155x221.bmp/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/170x164.png/5fa2dd/ffffff",
    "max_guests": 7,
    "pet_friendly": true,
    "pool": true,
    "wifi": true
  }, {
    "name": "Paradoxurus hermaphroditus",
    "slug": "Up-sized",
    "description": "Donec dapibus. Duis at velit eu est congue elementum.",
    "location": "6 Packers Road",
    "price": 31.07,
    "image": "http://dummyimage.com/207x203.jpg/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/106x229.png/cc0000/ffffff",
    "max_guests": 2,
    "pet_friendly": true,
    "pool": false,
    "wifi": false
  }, {
    "name": "Macaca mulatta",
    "slug": "Triple-buffered",
    "description": "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
    "location": "443 Mendota Center",
    "price": 34.91,
    "image": "http://dummyimage.com/126x185.png/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/232x247.jpg/dddddd/000000",
    "max_guests": 3,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Anas bahamensis",
    "slug": "open system",
    "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
    "location": "4038 La Follette Way",
    "price": 46.95,
    "image": "http://dummyimage.com/227x125.jpg/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/216x171.jpg/5fa2dd/ffffff",
    "max_guests": 3,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Choloepus hoffmani",
    "slug": "User-centric",
    "description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
    "location": "53 Southridge Plaza",
    "price": 53.26,
    "image": "http://dummyimage.com/228x214.jpg/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/248x226.jpg/ff4444/ffffff",
    "max_guests": 2,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Dusicyon thous",
    "slug": "24/7",
    "description": "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "location": "3749 Division Drive",
    "price": 47.52,
    "image": "http://dummyimage.com/183x172.bmp/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/117x179.jpg/ff4444/ffffff",
    "max_guests": 6,
    "pet_friendly": true,
    "pool": false,
    "wifi": false
  }, {
    "name": "Tadorna tadorna",
    "slug": "Mandatory",
    "description": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "location": "754 Kingsford Way",
    "price": 30.71,
    "image": "http://dummyimage.com/153x219.jpg/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/131x241.jpg/ff4444/ffffff",
    "max_guests": 7,
    "pet_friendly": false,
    "pool": true,
    "wifi": false
  }, {
    "name": "Colobus guerza",
    "slug": "Switchable",
    "description": "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.",
    "location": "2731 Sommers Alley",
    "price": 37.74,
    "image": "http://dummyimage.com/105x126.jpg/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/121x203.bmp/cc0000/ffffff",
    "max_guests": 4,
    "pet_friendly": false,
    "pool": true,
    "wifi": true
  }, {
    "name": "Tamiasciurus hudsonicus",
    "slug": "regional",
    "description": "Vivamus vestibulum sagittis sapien.",
    "location": "97 Havey Place",
    "price": 63.53,
    "image": "http://dummyimage.com/131x220.jpg/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/134x213.bmp/ff4444/ffffff",
    "max_guests": 4,
    "pet_friendly": true,
    "pool": false,
    "wifi": false
  }, {
    "name": "Corvus brachyrhynchos",
    "slug": "Customer-focused",
    "description": "Phasellus in felis.",
    "location": "44 Onsgard Crossing",
    "price": 69.79,
    "image": "http://dummyimage.com/208x216.jpg/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/122x101.jpg/cc0000/ffffff",
    "max_guests": 5,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Plocepasser mahali",
    "slug": "asymmetric",
    "description": "Vestibulum sed magna at nunc commodo placerat.",
    "location": "82 Riverside Hill",
    "price": 52.9,
    "image": "http://dummyimage.com/160x144.jpg/ff4444/ffffff",
    "image_thumbnail": "http://dummyimage.com/241x246.png/ff4444/ffffff",
    "max_guests": 2,
    "pet_friendly": true,
    "pool": false,
    "wifi": true
  }, {
    "name": "Paroaria gularis",
    "slug": "Optimized",
    "description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.",
    "location": "7896 Bowman Hill",
    "price": 51.3,
    "image": "http://dummyimage.com/237x226.bmp/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/120x246.jpg/cc0000/ffffff",
    "max_guests": 8,
    "pet_friendly": true,
    "pool": true,
    "wifi": true
  }, {
    "name": "Butorides striatus",
    "slug": "capability",
    "description": "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    "location": "7 Lotheville Drive",
    "price": 53.19,
    "image": "http://dummyimage.com/154x202.png/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/160x196.jpg/5fa2dd/ffffff",
    "max_guests": 8,
    "pet_friendly": false,
    "pool": false,
    "wifi": false
  }, {
    "name": "Grus canadensis",
    "slug": "zero administration",
    "description": "Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    "location": "91512 American Ash Point",
    "price": 36.76,
    "image": "http://dummyimage.com/234x207.bmp/dddddd/000000",
    "image_thumbnail": "http://dummyimage.com/117x217.png/cc0000/ffffff",
    "max_guests": 6,
    "pet_friendly": true,
    "pool": true,
    "wifi": false
  }, {
    "name": "Pterocles gutturalis",
    "slug": "project",
    "description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.",
    "location": "9325 Pond Hill",
    "price": 56.87,
    "image": "http://dummyimage.com/213x129.jpg/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/113x215.bmp/ff4444/ffffff",
    "max_guests": 3,
    "pet_friendly": false,
    "pool": false,
    "wifi": true
  }, {
    "name": "Parus atricapillus",
    "slug": "Secured",
    "description": "Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "location": "73 Almo Circle",
    "price": 60.61,
    "image": "http://dummyimage.com/144x167.png/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/152x210.png/5fa2dd/ffffff",
    "max_guests": 7,
    "pet_friendly": false,
    "pool": false,
    "wifi": false
  }, {
    "name": "Ictonyx striatus",
    "slug": "leading edge",
    "description": "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    "location": "0 Hollow Ridge Street",
    "price": 38.19,
    "image": "http://dummyimage.com/236x127.bmp/cc0000/ffffff",
    "image_thumbnail": "http://dummyimage.com/245x119.bmp/5fa2dd/ffffff",
    "max_guests": 4,
    "pet_friendly": false,
    "pool": true,
    "wifi": false
  }, {
    "name": "Odocoileus hemionus",
    "slug": "foreground",
    "description": "Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
    "location": "00 Harbort Park",
    "price": 65.91,
    "image": "http://dummyimage.com/119x223.jpg/5fa2dd/ffffff",
    "image_thumbnail": "http://dummyimage.com/141x241.png/ff4444/ffffff",
    "max_guests": 3,
    "pet_friendly": false,
    "pool": true,
    "wifi": false
  }]

  stay_list.each do |stay| Stay.create( stay )
  end